@startuml Diagrama de Classe Login



 entity  "Usuario"
 {  
   

    +char[16] CPF; 
    +string senha_cadastro;

    -void cadastro_usuario();
    -void excluir_usuario();
    +void login_usuario();
    


    


 }

class "Login"
{
    +char[16] CPF_login;

    +string senha_login;
    
    +void entry_login();

}

class "Autenticacao"
{
    -boolean autenticacao();

}

interface "Menu"
{
    +void cadastro_paciente();

    +void evolução_prontuario();

    +void finalizar_prontuario();

    +void busca_prontuario();

    +void fila_atendimento();

    -boolean autenticacao();

}


Login..>Autenticacao

Autenticacao -left..> Usuario
Autenticacao ..|> Menu



@enduml