@startuml Diagrama de Caso de Uso Administrador


skinparam actorStyle awesome

"Main Admin" as Admin

Admin -right-- (Realizar\nLogin)

(Realizar\nLogin)-right..>(Autenticação\n--\nextend points\n\nCadastrar\nExcluir\nEditar\nVisualizar\nControle) :: <<include>>

(Autenticação\n--\nextend points\n\nCadastrar\nExcluir\nEditar\nVisualizar\nControle)<.. (Cadastrar Profissional) :: <<extend>>

(Autenticação\n--\nextend points\n\nCadastrar\nExcluir\nEditar\nVisualizar\nControle)<.. (Excluir Profissional)  :: <<extend>>


(Autenticação\n--\nextend points\n\nCadastrar\nExcluir\nEditar\nVisualizar\nControle)<.. (Editar Profissional) :: <<extend>>

(Autenticação\n--\nextend points\n\nCadastrar\nExcluir\nEditar\nVisualizar\nControle)<.. (Visualizar Profissional) :: <<extend>>

(Autenticação\n--\nextend points\n\nCadastrar\nExcluir\nEditar\nVisualizar\nControle)<.. (Controle Banco de dados) :: <<extend>>


@endluml
